sudo: required
services:
  - docker:

before_install:
  - docker build -t chauhany/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true chauhany/react-test npm test

after_success:
  - docker build -t chauhany/multi-client ./client
  - docker build -t chauhany/multi-nginx ./nginx
  - docker build -t chauhany/multi-server ./server
  - docker build -t chauhany/multi-worker ./worker

    # Log in to docker cli

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # Take those images and push to docker HUB

  - docker push chauhany/multi-client
  - docker push chauhany/multi-nginx
  - docker push chauhany/multi-server
  - docker push chauhany/multi-worker


deploy:
  edge: true

  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-575175452525"
  bucket_path: "docker-multi"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
