sudo: required
services:
  - docker:

before_install:
  - docker build -t yashchauhan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true yashchauhan/react-test npm test

after_success:
  - docker build -t yashchauhan/multi-client ./client
  - docker build -t yashchauhan/multi-nginx ./nginx
  - docker build -t yashchauhan/multi-server ./server
  - docker build -t yashchauhan/multi-worker ./worker

    # Log in to docker cli

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # Take those images and push to docker HUB

  - docker push yashchauhan/multi-client
  - docker push yashchauhan/multi-nginx
  - docker push yashchauhan/multi-server
  - docker push yashchauhan/multi-worker
